#!/bin/bash

set -e

usage() {
	cat << EOF
USAGE:
	note [-c path] [-i course path][-nos] 

PARAMETERS
	-c <path (optional)>
		Compiles all .md files to pdf in the directory of the given path. 
		If a path is not given the .md files in the current directory are compiled.
		
	-i <course name> <path (optional)>
		Initiates a skeleton directory for a new course from the directory given in path. 
		If a path is not given the skeleton directory is created in the current directory.

	-n 
		Creates a new "skeleton" markdown note file. 
	
	-o
		Opens the latest note session in the current directory.
	
	-s 
		Search the given course for a string.	

EOF
}

outputToPDF() { echo "In output to pdf with argument: $1";}
newCourse() { echo "In new course with arguments: $1 $2";}
newSession() { echo "In new session";}
checkLastSession() { echo "In checkLastSession";}
openLastSession() { echo "In open last session";}
search() { echo "In search: $1"; }

PARSED_OPTIONS=$(getopt c::i:nos: $*)
set -- $PARSED_OPTIONS

if [ $# -eq 1 ]; then
	usage
fi
for arg do
	case "$arg" in
		-c)
			echo "c was given"
			shift; shift
			if [ -z $1 ]; then
				outputToPDF "."
			else
				outputToPDF $1
			fi
		;;
		-i)
			echo "i was given"
			shift
			course=$1
			shift; shift
			path=$1
			if [ -z $path ]; then
				newCourse $course "." 
			else
				newCourse $course $path
			fi
		;;
		-n)
			echo "n was given"
			newSession
			shift
		;;
		-o)
			echo "o was given"
			openLastSession
			shift
		;;
		-s)
			echo "s was given"
			shift
			if [ -z $1 ]; then
				echo "Error: Search pattern required."
			else
				search $1
			fi
			shift
		;;
	esac
done
